title: open.fusioncode.eu
theme: jekyll-theme-architect

JB :
version : 0.3.0
  analytics :
    provider : google_tags
    google :
      tracking_id : 'UA-127076897-2'
    google_tags :
      tag_id : 'GTM-MJ4J7HQ'
